version: "3"

services:
  redis:
    image: redis:6.0.7
    container_name: redis_attrs
    ports:
        - 80:80
    volumes:
      - ./redis-command:/data/redis-command
    command:
      "--loglevel debug"
    logging:
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        max-size: "20k"
        max-file: "5"
        compress: "true"